### ISSUE TITLE
Breaks on flutter master/alpha

### ISSUE THREAD

**Issue by drewwarren** [dart-lang/usage#78]
```
E/flutter : [ERROR:dart_error.cc(17)] Unhandled exception:
E/flutter : No top-level method 'getFilesDir' declared.
E/flutter : 
E/flutter : NoSuchMethodError: method not found: 'getFilesDir'
E/flutter : Receiver: top-level
E/flutter : Arguments: [...]
E/flutter : #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:169)
E/flutter : #1      createAnalytics.<createAnalytics_async_body> (package:usage/src/usage_impl_flutter.dart:22)
E/flutter : #2      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
E/flutter : #3      _microtaskLoop (dart:async/schedule_microtask.dart:41)
E/flutter : #4      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
```

https://github.com/dart-lang/usage/blob/775bffd3a0c966e4dbc4e3e2c9fd6e29c079c054/lib/src/usage_impl_flutter.dart#L22

getFilesDir was removed from flutter in https://github.com/flutter/flutter/pull/3636

**Comment by devoncarew** [comment]
Thanks for letting us know! We should get the flutter portion of this under test.

**Comment by devoncarew** [comment]
fixed by https://github.com/dart-lang/usage/pull/79

**Comment by devoncarew** [comment]
@drewwarren, can you try the latest published version and see if it works for you? Thanks!

**Comment by drewwarren** [comment]
Perfect. Thanks Devon!
